### ISSUE TITLE
Update Connect Project model with Reference code and Project type

### ISSUE THREAD

**Issue by fnisen** [topcoder-platform/looker#21]
Currently "Ref code" and "Project type" are stored in the project details json doc, which is created for each project. I'd like these set up as "Dimensions," so they can be easily accessed in Looks/Dashboards.

Addition: let's also extract the "Cancelation reason." I'm not sure whether it's also stored in the json doc, but @vikasrohit can help locate it.

**Comment by fnisen** [comment]
@RiteshAppirio would you be able to work on this issue this week? We've just released a new version of Connect and need to report on these metrics.

**Comment by fnisen** [comment]
Adding some context from @ajefts: 
- We were able to set up the json functions correctly in Looker, but the AWS DMS job is truncating the needed columns
- Things should have worked correctly b/c DMS does support migrating the full LOB columns for Redshift
- No idea what's going wrong... may need to load the tables a different way

**Comment by RiteshTC** [comment]
@fnisen @ajefts 
My apologies, I am bit tied this week, due to SFDC  new org go live on 4/1. I will be able to start work on it, most probably by end of  next week.

**Comment by fnisen** [comment]
Thanks for the quick reply Ritesh. Totally understand. Is there anyone else available from Sumit's team who can help or are all of you guys fully booked with SFDC?

**Comment by RiteshTC** [comment]
@fnisen I will check with Sumit, when I am in office, later in the day.

**Comment by RiteshTC** [comment]
@fnisen I have checked with Sumit, and it seems like, the team is short on bandwidth. Most likely we can take this up after SFDC go live (tentative date 4/3).

**Comment by RiteshTC** [comment]
Hi @ajefts 
I tried working on the dev environment, related to this, but didn't have permissions to create DMS services. Questions
1. Is it okay for vikas to grant permissions in the dev environment to my user ?

Vikas and I checked the settings in production related to the DMS task. The LOB Settings are set to truncate at 63KB. Is it possible to change them to edit them and make them Full LOB ?
We haven't change anything in prod yet.

Please check the screenshots
<img width="690" alt="lobsetting" src="https://cloud.githubusercontent.com/assets/5771673/24653214/88a4338c-1952-11e7-9ddd-f2e3f43e469d.png">
<img width="912" alt="log" src="https://cloud.githubusercontent.com/assets/5771673/24653219/8cb3814e-1952-11e7-94c7-5c0579fcc75b.png">

cc @vikasrohit

**Comment by fnisen** [comment]
@RiteshAppirio Vikas can definitely grant you permission.

I'm not sure about the full LOB mode, but I think it's fine. Will bug Tony to reply. Thanks.

**Comment by ajefts** [comment]
1.  Yes, definitely.
2. For the LOB settings, I believe the issue is that DMS doesn't support Full LOB with Redshift as a target.  So, I think we need another approach to load large text columns into Redshift...

**Comment by RiteshTC** [comment]
oh yes DMS supports a max of 63KB. 
I believe I will need to update the JAVA code to run a job for Connect projects as well.
Currently I am battling some post production migration issues, will be working on it next week.

**Comment by fnisen** [comment]
Hi @RiteshAppirio. Any updates on this please?

**Comment by RiteshTC** [comment]
@fnisen Very sorry, I haven't been able to work on it much,  due to issues in new SFDC org.
I did some research and the most likely short term approach would be to update the JAVA code (that copies data from Informix to Redshift) to include another connection for Postgres Connect data). I haven't had a chance to validate and test the approach yet

**Comment by fnisen** [comment]
Thanks @RiteshAppirio, no worries, please let me know as you pick this up. I'd like to also have you pull out the "Cancelation reason," which we recently added. I've added it in the initial comments above. Vikas can help b/c he implemented it in the Connect code.

**Comment by RiteshTC** [comment]
Hi @fnisen 
I and Vikas spent considerable time on the issue, in the dev environment.
It seems like, the issue lies with Amazon DMS Service, which is unable to load JSON string greater than 255 characters.

We are working on adding code (for Connect Postgres Data)  to the existing TCS Loader, which loads existing Informix data.  
We will be testing this in dev environment and reviewing the process with Tony early next week. 
If everything goes well, we should be able to deploy it by end of next week

**Comment by fnisen** [comment]
Perfect, thank you guys. Please let me know how it goes.

**Comment by fnisen** [comment]
@RiteshTC what's the status of this ticket please? I know we pushed some updates here https://github.com/topcoder-platform/tcs-loader/pull/10, but it seems like these were just to dev. I'm not seeing some of the new fields in prod, like reference code and cancellation reason.

**Comment by RiteshTC** [comment]
@ajefts is it good to push in production ?
can you help us get it deployed in production

**Comment by RiteshTC** [comment]
@fnisen 
This should now be in production looker.

cc @vikasrohit

**Comment by fnisen** [comment]
@RiteshTC I've been playing around with this a little bit and see the project details coming through, but I still need a few of the data fields set up as Dimensions. Would you be able to do this? Specifically, I need "Ref code" and "Cancellation reason" extracted as Dimensions, so they can be easily used for filtering in Looker dashboards. Thank you.

**Comment by RiteshTC** [comment]
@fnisen 
I have done the change in the Looker.xml file with help of @DevPassionSK 
Ref code and Cancellation Reason should now be available as dimensions

cc @ajefts

**Comment by fnisen** [comment]
Thank you @RiteshTC and @DevPassionSK. It's working.
