### ISSUE TITLE
connect project members issue

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/looker#32]
The loader for connect project_members is not loading the project_id.

**Comment by ajefts** [comment]
@DevPassionSK can you fix this one please?

**Comment by ajefts** [comment]
fyi @RiteshTC

**Comment by shashank-khatri** [comment]
@ajefts Made relevant changes to the code to update project_id. Couldn't run the script as I don't have permission to do it.

**Comment by ajefts** [comment]
@DevPassionSK Did you build and deploy to prod?
