### ISSUE TITLE
Bring Mailchimp User Data into Looker

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/looker#34]
@ajefts had mentioned that the data about which tracks a member has registered with Topcoder with was being logged in Mailchimp and that it should be moved over to Looker.  The community team needs to gather this information to know who to send our drip campaign emails to.

Thanks!

**Comment by ajefts** [comment]
This could first, and more generically, be accomplished by pulling in data from the memberProfile records in Dynamo.  This includes the Dev/Design/Data as well as other attributes that we don't yet have in Redshift

**Comment by RiteshTC** [comment]
Done Member Newsletter Preferences and Member Profile Data is available in Looker.
