### ISSUE TITLE
extract fields for topgear in model

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/looker#38]
We have some new fields being passed into Connect projects that come in via Topgear.  They end up in the "details" field on the Connect Projects, which is really just a big json object.  

Please parse out each of the following fields into their own dimension. You can see examples of this done for other fields in https://topcoder.looker.com/projects/topcoder_data_warehouse/files/projects.view.lkml (line 197)

Example detail field:
```
{"products":["application_development"],"utm":{"code":"topgear"},"appDefinition":{"primaryTarget":"desktop","goal":{"value":"TBD"},"users":{"value":"Description of target users."}},"hideDiscussions":true,"project_data":{"customer_project":"Yes","du":"NA","group_customer_name":"NA","project_code":"NA","cost_center":"MD5311","wbs_code":"NA","onsite_efforts":"12","offshore_efforts":"5","planned_start_date":"1527618600","planned_end_date":"1527705000","part_of_ng3":"No"}}
```

The fields we need to parse are:

"customer_project":"Yes","du":"NA","group_customer_name":"NA","project_code":"NA","cost_center":"MD5311","wbs_code":"NA","onsite_efforts":"12","offshore_efforts":"5","planned_start_date":"1527618600","planned_end_date":"1527705000","part_of_ng3":"No"

**Comment by ajefts** [comment]
@RiteshTC Can we get this one done in the next few days?  It's a model update in looker....

**Comment by RiteshTC** [comment]
Done and deployed 
Sample https://topcoder.looker.com/looks/959
