### ISSUE TITLE
Add Effort Hours to Redshift loader

### ISSUE THREAD

**Issue by ajefts** [topcoder-platform/looker#39]
We have a new attribute on challenges that we need to load to redshift.  It is called "Effort Hours" and is stored in the project_info table in oltp.  This needs to be added to the loader so we have the field as a challenge measure in redshift/looker.

**Comment by ajefts** [comment]
@RiteshTC Can you guys give an estimate on this one?

**Comment by RiteshTC** [comment]
@ajefts 
We will try to get this in place by next Monday (11th Jun).

**Comment by RiteshTC** [comment]
@ajefts 
This has been done and deployed. All old data should be available in next run.
