### ISSUE TITLE
Add fields in Connect Projects to support additional data

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/looker#50]
1) Monitoring template usage by project (i.e. what templates are selected and used most frequently, by project type).
2) Monitoring free form inputs into templates (i.e. copilots can adjust template titles/descriptions), by projects.
3) Monitoring the phase duration that is input by the copilot into the template.
4) Monitoring the phase budget that is input by the copilot into the template.
5) Monitoring failure rates of product (phase) templates - i.e. failures to load, etc.

**Comment by Himanshu-Bhansali** [comment]
Hey @acshields 

Please check the [report](https://topcoder.looker.com/looks/1159) out for Connect project phase template and budget details. Please let us know in case of any questions/concerns.

Thanks!
cc: @RiteshTC
