### ISSUE TITLE
Looker Data to Be Used In Contentful

### ISSUE THREAD

**Issue by hokienick** [topcoder-platform/looker#51]
Hey there!  Would love to eventually know how to do this as I foresee needing to do something similar often, but here is the ask:

I have [this dashboard](https://topcoder.looker.com/dashboards/150) here that I would like converted in such a way that I'd be able to pull data from it and display it on a page in Contentful.  I have a member who can help me with getting the data to display, just not sure how to go about obtaining it.  And just to be clear the data should be live and updated at a minimum of 1 day.

Thanks!

**Comment by Himanshu-Bhansali** [comment]
Hey @hokienick ,

Thanks for reaching out! There are two options for getting the data - 

1. Download the dashboard as PDF or CSV - but the limitation to that is, it will not show complete data and it just takes a snapshot.
2. Download the individual looks on the Dashboard - easier to pull data for Contentful and shows complete data - When you hover over a particular tile in dashboard, there are three dots (top right corner of tile) that gives you an option to download the look behind the tile (see screenshot) and then you can download it in your desired format. 

![image](https://user-images.githubusercontent.com/38908597/44456437-24b6f580-a61e-11e8-9dfa-34ae73a426f5.png)

I have downloaded the same for you and attaching them here. you can refer to [this manual](https://docs.looker.com/sharing-and-publishing/downloading) for next download.

Please let me know if this works. Thanks!

cc: @RiteshTC 

[Members Paid 2018-08-22T1506.xlsx](https://github.com/topcoder-platform/looker/files/2309760/Members.Paid.2018-08-22T1506.xlsx)
[Copiloted Challenges 2018-08-22T1506.xlsx](https://github.com/topcoder-platform/looker/files/2309761/Copiloted.Challenges.2018-08-22T1506.xlsx)
[Completed Challenges 2018-08-22T1505.xlsx](https://github.com/topcoder-platform/looker/files/2309762/Completed.Challenges.2018-08-22T1505.xlsx)
[Prizes Awarded 2018-08-22T1505.xlsx](https://github.com/topcoder-platform/looker/files/2309763/Prizes.Awarded.2018-08-22T1505.xlsx)
[Member Count 2018-08-22T1505.xlsx](https://github.com/topcoder-platform/looker/files/2309764/Member.Count.2018-08-22T1505.xlsx)
[Submitters by Country 2018-08-22T1507.xlsx](https://github.com/topcoder-platform/looker/files/2309765/Submitters.by.Country.2018-08-22T1507.xlsx)
[Dev Technologies Count 2018-08-22T1506.xlsx](https://github.com/topcoder-platform/looker/files/2309766/Dev.Technologies.Count.2018-08-22T1506.xlsx)
[Country First Place Wins 2018-08-22T1506.xlsx](https://github.com/topcoder-platform/looker/files/2309767/Country.First.Place.Wins.2018-08-22T1506.xlsx)
[First Place Wins 2018-08-22T1506.xlsx](https://github.com/topcoder-platform/looker/files/2309768/First.Place.Wins.2018-08-22T1506.xlsx)
[Countries Represented 2018-08-22T1506.xlsx](https://github.com/topcoder-platform/looker/files/2309769/Countries.Represented.2018-08-22T1506.xlsx)

**Comment by hokienick** [comment]
Thanks for looking into this!  I am actually attempting to go in another direction with API Endpoints.  I will close this issue and open another in regards to Looker.  Going to need to add to this dashboard :)
