### ISSUE TITLE
Check If TCLoadSubmission is loading URL

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/looker#65]
Please load the submission URL is TC Load class, if not already loaded.

**Comment by RiteshTC** [comment]
@m-yadav 
1. Lets rename to the column for "submission_url_s3" to "submission_url_external" in database, as the submissions might be stored externally as well.
2. A separate script file is not needed. Please add the modification in 09_adhoc tables script

**Comment by m-yadav** [comment]
@RiteshTC 

1.Lets rename to the column for "submission_url_s3" to "submission_url_external" in database, as the submissions might be stored externally as well. -- **Done**

2.A separate script file is not needed. Please add the modification in 09_adhoc tables script -- **Done**

Have pushed the changes in feature/s3SubmissionUrl
