### ISSUE TITLE
Create Script to Vaccuum all Tables in Redshift

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/looker#67]
Create a sql script to vaccuum all tables in Redshift.
This needs to be run every 30 days to clear space in Redshift

**Comment by RiteshTC** [comment]
@m-yadav 
Can you please recheck this ? It seems to be running in loop. 
Also, it would be helpful to sort by schema name, and then by table name to see the progress

**Comment by m-yadav** [comment]
@RiteshTC the result set is now sorted by schema name, table name.
The select query has been altered and now only picking distinct results.
